[package]
name = "imt-user"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bitflags = "2.10.0"
lilium-sys = { git = "https://github.com/LiliumOS/lilium-sys", default-features = false }
